name: rm_systems_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  # Adicione esta linha
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.2.0
  shared_preferences: ^2.3.2
  dio: ^5.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.0.0
  email_validator: ^2.1.17
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  mockito: ^5.4.4 
  build_runner: ^2.4.11 


flutter:
  uses-material-design: true
  assets:
    - assets/logo-removed.png
    # - assets/login/login_icon.png
    # - assets/login/login_top.png
    # - assets/login/login_bottom.png